# Generated by Django 5.0.1 on 2024-02-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_fileupload"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileupload",
            name="title",
            field=models.CharField(default="", max_length=50),
        ),
    ]
